defaults: &defaults
  docker:
    - image: circleci/android:api-29
  working_directory: ~/code
default-env: &defaultEnv
  JVM_OPTS: -Xmx3200m
  _JAVA_OPTIONS: -Xmx1536m

version: 2.1
jobs:
  test:
    <<: *defaults
    environment:
      <<: *defaultEnv
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Create Local Properties
          command: touch local.properties
      - run:
          name: Add Api Keys
          command: |
            echo -e "weatherApiKey=\"$WEATHER_API_KEY\"\n" >> local.properties
            echo -e "newsApiKey=\"$NEWS_API_KEY\"\n" >> local.properties
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew testDebugUnitTest --console=plain
  build-apk:
    <<: *defaults
    environment:
      <<: *defaultEnv
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Create Local Properties
          command: touch local.properties
      - run:
          name: Add Api Keys
          command: |
            echo -e "weatherApiKey=\"$WEATHER_API_KEY\"\n" >> local.properties
            echo -e "newsApiKey=\"$NEWS_API_KEY\"\n" >> local.properties
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      - run:
          name: Build Debug Apk
          command: ./gradlew --console=plain assembleDebug
      - run:
          name: Stash APK
          command: |
            APK_NAME="app-debug.apk"
            APK_PATH="./app/build/outputs/apk/debug/$APK_NAME"
            mkdir ~/workspace
            cp $APK_PATH ~/workspace/$APK_NAME
      - persist_to_workspace:
          root: ~/workspace
          paths:
            - "*apk"
  tag-debug-release:
    <<: *defaults
    environment:
      <<: *defaultEnv
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Create Tag
          command: |
            VNAME=$(grep 'versionName\s' app/build.gradle | tr -d ' "[a-zA-Z]')
            BODY=$(git cherry -v develop)
            ghr -t "$GITHUB_TOKEN" -u "$CIRCLE_USERNAME" -prerelease -b "$BODY" "v$VNAME-$CIRCLE_BUILD_NUM-debug" /tmp/workspace

workflows:
  version: 2.1
  build:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - master
                - develop
      - build-apk:
          filters:
            branches:
              only:
                - develop
                - master
      - tag-debug-release:
          requires:
            - build-apk
          filters:
            branches:
              only: develop
